import * as fs from 'fs';
import * as path from 'path';

export async function generateNext(projectPath: string, projectName: string, useTypeScript: boolean = true) {
  if (useTypeScript) {
    await generateNextTS(projectPath, projectName);
  } else {
    await generateNextJS(projectPath, projectName);
  }
}

// ─── TypeScript Version ───────────────────────────────────────────────────────

async function generateNextTS(projectPath: string, projectName: string) {
  const packageJson = {
    name: projectName,
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "next lint"
    },
    dependencies: {
      next: "^15.1.0",
      react: "^19.0.0",
      "react-dom": "^19.0.0"
    },
    devDependencies: {
  "@types/node": "^22",
  "@types/react": "^19",
  "@types/react-dom": "^19",
  "eslint": "^9",
  "eslint-config-next": "^15.1.0",
  "postcss": "^8",
  "autoprefixer": "^10.4.20",  // ← add this
  "tailwindcss": "^3.4.0",
  "typescript": "^5"
}
  };

  const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {}

export default nextConfig
`;

  const tsConfig = `{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "baseUrl": ".",
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`;

  const tailwindConfig = `import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
export default config
`;

  const postcssConfig = `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;

  const layoutTsx = `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by WebInit 🚀',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
`;

const pageTsx = `export default function Home() {
  return (
    <main className="min-h-screen bg-[#0f0f11] flex items-center justify-center px-6">
      <div className="max-w-xl w-full text-center">
        <div className="bg-white/5 border border-white/10 rounded-3xl p-12 shadow-[0_20px_80px_-20px_rgba(0,0,0,0.6)] backdrop-blur-xl transition-all duration-500 hover:scale-[1.02]">
          <h1 className="text-4xl font-semibold text-white tracking-tight mb-4">
            Thanks for using WebInit
          </h1>
          <p className="text-gray-400 text-base mb-8">
            Next.js · TypeScript · Tailwind CSS
            <br />
            Built for speed. Designed for simplicity.
          </p>
          <a
            href="https://nextjs.org/docs"
            className="px-7 py-2.5 rounded-full bg-white text-black text-sm font-medium hover:opacity-90 transition-all duration-300"
          >
            Read the Docs
          </a>
        </div>
      </div>
    </main>
  )
}
`;

  const globalsCss = `@tailwind base;
@tailwind components;
@tailwind utilities;`;

  const gitignore = `node_modules\n.next\n.env\n.env.local\n.DS_Store\n*.log`;

  fs.mkdirSync(path.join(projectPath, 'src', 'app'), { recursive: true });
  fs.mkdirSync(path.join(projectPath, 'public'), { recursive: true });

  const files: Record<string, string> = {
    'package.json': JSON.stringify(packageJson, null, 2),
    'next.config.mjs': nextConfig,
    'tsconfig.json': tsConfig,
    'tailwind.config.ts': tailwindConfig,
    'postcss.config.mjs': postcssConfig,
    'src/app/layout.tsx': layoutTsx,
    'src/app/page.tsx': pageTsx,
    'src/app/globals.css': globalsCss,
    '.gitignore': gitignore,
    'README.md': `# ${projectName}\n\nNext.js 15 + TypeScript + Tailwind CSS\n\n## Quick Start\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\nlocalhost:3000`
  };

  for (const [fileName, content] of Object.entries(files)) {
    fs.writeFileSync(path.join(projectPath, fileName), content);
  }
}

// ─── JavaScript Version ───────────────────────────────────────────────────────

async function generateNextJS(projectPath: string, projectName: string) {
  const packageJson = {
    name: projectName,
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "next lint"
    },
    dependencies: {
      next: "^15.1.0",
      react: "^19.0.0",
      "react-dom": "^19.0.0"
    },
    devDependencies: {
  "eslint": "^9",
  "eslint-config-next": "^15.1.0",
  "postcss": "^8",
  "autoprefixer": "^10.4.20",
  "tailwindcss": "^3.4.0",
}
  };

  const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {}

export default nextConfig
`;

  const tailwindConfig = `/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    './src/pages/**/*.{js,jsx,mdx}',
    './src/components/**/*.{js,jsx,mdx}',
    './src/app/**/*.{js,jsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
export default config
`;

  const postcssConfig = `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;

  const layoutJsx = `import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '${projectName}',
  description: 'Generated by WebInit 🚀',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
`;

const pageJsx = `export default function Home() {
  return (
    <main className="min-h-screen bg-[#0f0f11] flex items-center justify-center px-6">
      <div className="max-w-xl w-full text-center">
        <div className="bg-white/5 border border-white/10 rounded-3xl p-12 shadow-[0_20px_80px_-20px_rgba(0,0,0,0.6)] backdrop-blur-xl transition-all duration-500 hover:scale-[1.02]">
          <h1 className="text-4xl font-semibold text-white tracking-tight mb-4">
            Thanks for using WebInit
          </h1>
          <p className="text-gray-400 text-base mb-8">
            Next.js · JavaScript · Tailwind CSS
            <br />
            Built for speed. Designed for simplicity.
          </p>
          <a
            href="https://nextjs.org/docs"
            className="px-7 py-2.5 rounded-full bg-white text-black text-sm font-medium hover:opacity-90 transition-all duration-300"
          >
            Read the Docs
          </a>
        </div>
      </div>
    </main>
  )
}
`;

  const globalsCss = `@tailwind base;
@tailwind components;
@tailwind utilities;`;

  const gitignore = `node_modules\n.next\n.env\n.env.local\n.DS_Store\n*.log`;

  fs.mkdirSync(path.join(projectPath, 'src', 'app'), { recursive: true });
  fs.mkdirSync(path.join(projectPath, 'public'), { recursive: true });

  const files: Record<string, string> = {
    'package.json': JSON.stringify(packageJson, null, 2),
    'next.config.mjs': nextConfig,
    'tailwind.config.js': tailwindConfig,
    'postcss.config.mjs': postcssConfig,
    'src/app/layout.jsx': layoutJsx,
    'src/app/page.jsx': pageJsx,
    'src/app/globals.css': globalsCss,
    '.gitignore': gitignore,
    'README.md': `# ${projectName}\n\nNext.js 15 + JavaScript + Tailwind CSS\n\n## Quick Start\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\nlocalhost:3000`
  };

  for (const [fileName, content] of Object.entries(files)) {
    fs.writeFileSync(path.join(projectPath, fileName), content);
  }
  }