import * as fs from 'fs';
import * as path from 'path';

export async function generateNext(projectPath: string, projectName: string) {
    // 1. package.json (Next.js 15 App Router + TS)
    const packageJson = {
        name: projectName,
        version: "0.1.0",
        private: true,
        scripts: {
            "dev": "next dev",
            "build": "next build",
            "start": "next start",
            "lint": "next lint"
        },
        dependencies: {
            "next": "15.0.0-canary.*",
            "react": "^19.0.0",
            "react-dom": "^19.0.0"
        },
        devDependencies: {
            "@types/node": "^20",
            "@types/react": "^19",
            "@types/react-dom": "^19",
            "eslint": "^9",
            "eslint-config-next": "15.0.0-canary.*",
            "postcss": "^8",
            "tailwindcss": "^3.4.0",
            "typescript": "^5"
        }
    };

    // 2. next.config.mjs
    const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    typedRoutes: true,
  },
}

export default nextConfig
`;

    // 3. tsconfig.json
    const tsConfig = `{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "es7"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`;

    // 4. tailwind.config.ts
    const tailwindConfig = `import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
export default config
`;

    // 5. postcss.config.mjs
    const postcssConfig = `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;

    // 6. src/app/layout.tsx
    const layoutTsx = `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by WebInit 🚀',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
`;

    // 7. src/app/page.tsx (Your WebInit branding!)
    const pageTsx = `export default function Home() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-purple-500 to-indigo-600 flex flex-col items-center justify-center text-white p-8">
      <div className="text-center max-w-4xl mx-auto">
        <h1 className="text-6xl font-black mb-12 bg-gradient-to-r from-white to-gray-200 bg-clip-text text-transparent drop-shadow-2xl">
          Thanks for using WebInit 🚀
        </h1>
        <div className="grid md:grid-cols-2 gap-12 items-center">
          <div>
            <h2 className="text-3xl font-bold mb-8">Next.js 15 + TypeScript</h2>
            <p className="text-xl opacity-90 mb-8 leading-relaxed">
              App Router • Server Components • TypeScript • Tailwind CSS
            </p>
            <div className="flex flex-wrap gap-4">
              <code className="bg-white/20 backdrop-blur-sm px-4 py-2 rounded-xl font-mono text-lg border border-white/30">
                npm run dev
              </code>
              <span className="text-2xl opacity-75">→ localhost:3000</span>
            </div>
          </div>
          <div className="card bg-white/10 backdrop-blur-xl rounded-3xl p-10 shadow-2xl border border-white/20 hover:scale-105 transition-all duration-500">
            <div className="text-4xl font-mono bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent mb-4">
              Next.js 15
            </div>
            <div className="space-y-3 text-lg">
              <div>✅ App Router</div>
              <div>✅ TypeScript</div>
              <div>✅ Tailwind CSS</div>
              <div>✅ Server Components</div>
            </div>
          </div>
        </div>
      </div>
    </main>
  )
}
`;

    // 8. src/app/globals.css
    const globalsCss = `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  html {
    scroll-behavior: smooth;
  }
}`;

    // 9. next-env.d.ts
    const nextEnvDts = `/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference types="next/navigation-types/compat/navigation.d.ts" />

/** Ensure this file is included in your tsconfig.json compilerOptions.types */
declare global {
  namespace NodeJS {
    interface ProcessEnv {
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string
    }
  }
}
`;

    // 10. .gitignore
    const gitignore = `node_modules
.next
/dist
.env
.env.local
.env.development.local
.env.test.local
.env.production.local
.DS_Store
*.log
`;

    // Write all files
    const files = {
        'package.json': JSON.stringify(packageJson, null, 2),
        'next.config.mjs': nextConfig,
        'tsconfig.json': tsConfig,
        'tailwind.config.ts': tailwindConfig,
        'postcss.config.mjs': postcssConfig,
        'next-env.d.ts': nextEnvDts,
        'src/app/layout.tsx': layoutTsx,
        'src/app/page.tsx': pageTsx,
        'src/app/globals.css': globalsCss,
        '.gitignore': gitignore,
        'README.md': `# ${projectName}\n\nNext.js 15 + TypeScript + App Router\n\n## Quick Start\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\nlocalhost:3000`
    };

    // Create directory structure
    const dirs = [
        path.join(projectPath, 'src', 'app'),
        path.join(projectPath, 'public', 'assets', 'images')
    ];
    
    for (const dir of dirs) {
        fs.mkdirSync(dir, { recursive: true });
    }

    // Write all files
    for (const [fileName, content] of Object.entries(files)) {
        fs.writeFileSync(path.join(projectPath, fileName), content);
    }
}
